#include "mapreduce.h"

int main(int argc, char *argv[]) {
	
	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(0);
	}

	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);
	char *inputFile = argv[3];

  if(nMappers < nReducers){
    printf("Number of Mappers less than Reducers");
    exit(0);
  }

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork();
  
	if(pid == 0){
		//send chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	} else if(pid == -1) {
      perror("Fork problem");
      exit(-1);
  }

	sleep(1);

  pid_t c; 
  char strID[50]; 
  int e; 
  int status;

	// To do
	// spawn mappers processes and run 'mapper' executable using exec
	for (int i =1 ; i < nMappers + 1; i++){
    pid_t c = fork(); 
    if(c >0){
      pid= waitpid(c, NULL, 0);
    }
    else if( c == 0 ) {
      // child
      sprintf(strID, "%d", i);
      e = execl( "./mapper", "./mapper", strID, NULL );
      if (e == -1){
        perror("Exec problem");
        exit(-1); 
      } else {exit(0);}
    }
    else if(pid == -1) {
      perror("Fork problem");
      exit(-1);
    }
  }

  int w;
	// wait for all children to complete execution
  for(int i =0; i<nMappers; i++){
    w = wait(NULL);
    if(w == -1){
      perror("Wait problem");
      exit(-1);
    }
  }
    

	// ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper 
    // to reducer based on a hash function
	pid = fork();
	if(pid == 0){
		shuffle(nMappers, nReducers);
		exit(0);
	} else if(pid == -1) {
      perror("Fork problem");
      exit(-1);
  }
	sleep(1);



	// spawn reducer processes and run 'reducer' executable using exec
  char strIDReduce[50];
  pid_t g; 
  
	for (int i =1 ; i < nReducers + 1; i++){
     g = fork(); 

    if( g == 0 ){
      sprintf(strIDReduce, "%d", i);
      e = execl( "./reducer", "./reducer" ,strIDReduce, NULL);
      exit(0);
      if (e == -1){
          perror("Exec problem");
          exit(-1);
      }
    } else if(pid == -1) {
      perror("Fork problem");
      exit(-1);
  }
  }

	// wait for all children to complete execution
  for(int i =0; i<nReducers; i++){
    w = wait(NULL);
    if (w == -1){
      perror("Wait problem");
      exit(-1);
    }
  }

	return 0;
}